/**
 * Copyright (c) 2024, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

export enum FieldConstants {
    ACTIVE_POWER_SET_POINT = 'activePowerSetpoint',
    ADDED = 'added',
    ADDITIONAL_PROPERTIES = 'AdditionalProperties',
    AG_GRID_ROW_UUID = 'agGridRowUuid',
    API_CALL = 'apiCall',
    BUS_OR_BUSBAR_SECTION = 'busOrBusbarSection',
    CASE_FILE = 'caseFile',
    CASE_FORMAT = 'caseFormat',
    CASE_NAME = 'caseName',
    CASE_UUID = 'caseUuid',
    CONNECTED = 'terminalConnected',
    CONNECTION_DIRECTION = 'connectionDirection',
    CONNECTION_NAME = 'connectionName',
    CONNECTION_POSITION = 'connectionPosition',
    CONNECTIVITY = 'connectivity',
    CONNECTIVITY_1 = 'connectivity1',
    CONNECTIVITY_2 = 'connectivity2',
    CONTINGENCY_LIST_TYPE = 'contingencyListType',
    CONTINGENCY_NAME = 'contingencyName',
    COUNTRIES_1 = 'countries1',
    COUNTRIES_2 = 'countries2',
    COUNTRIES = 'countries',
    COUNTRY = 'country',
    CURRENT_PARAMETERS = 'currentParameters',
    DELETION_MARK = 'deletionMark',
    DESCRIPTION = 'description',
    DIRECTORY = 'directory',
    ENERGY_SOURCE = 'energySource',
    EQUIPMENT_ID = 'equipmentID',
    EQUIPMENT_NAME = 'equipmentName',
    EQUIPMENT_IDS = 'equipmentIDs',
    EQUIPMENT_TABLE = 'equipmentTable',
    EQUIPMENT_TYPE = 'equipmentType',
    FILTER_TYPE = 'filterType',
    FILTERS = 'filters',
    FOLDER_ID = 'folderId',
    FOLDER_NAME = 'folderName',
    FORMATTED_CASE_PARAMETERS = 'formattedCaseParameters',
    ID = 'id',
    LOAD_TYPE = 'loadType',
    MAXIMUM_ACTIVE_POWER = 'maximumActivePower',
    MEASUREMENT_P = 'measurementP',
    MEASUREMENT_P1 = 'measurementP1',
    MEASUREMENT_P2 = 'measurementP2',
    MEASUREMENT_Q = 'measurementQ',
    MEASUREMENT_Q1 = 'measurementQ1',
    MEASUREMENT_Q2 = 'measurementQ2',
    MINIMUM_ACTIVE_POWER = 'minimumActivePower',
    NAME = 'name',
    NOMINAL_VOLTAGE_1 = 'nominalVoltage1',
    NOMINAL_VOLTAGE_2 = 'nominalVoltage2',
    NOMINAL_VOLTAGE_3 = 'nominalVoltage3',
    NOMINAL_VOLTAGE = 'nominalVoltage',
    OPERATION_TYPE = 'type',
    PREVIOUS_VALUE = 'previousValue',
    PROPERTY_NAME = 'propertyName',
    PROPERTY_OPERATOR = 'propertyOperator',
    PROPERTY = 'PROPERTY',
    PROPERTY_VALUES = 'propertyValues',
    REACTIVE_POWER_SET_POINT = 'reactivePowerSetpoint',
    SCRIPT = 'script',
    STATE_ESTIMATION = 'stateEstimation',
    STUDY_NAME = 'studyName',
    TYPE = 'type',
    VALIDITY = 'validity',
    VALUE = 'value',
    VALUE_1 = 'value1',
    VALUE_2 = 'value2',
    VOLTAGE_LEVEL = 'voltageLevel',
    VOLTAGE_REGULATION = 'voltageRegulation',
}
