/**
 * Copyright (c) 2024, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

export enum FieldConstants {
    ADD_SUBSTATION_CREATION = 'addSubstationCreationId',
    ADDED = 'added',
    ADDITIONAL_PROPERTIES = 'AdditionalProperties',
    AG_GRID_ROW_UUID = 'agGridRowUuid',
    API_CALL = 'apiCall',
    BUS_BAR_COUNT = 'busbarCount',
    BUS_BAR_SECTION_ID1 = 'busBarSectionId1',
    BUS_BAR_SECTION_ID2 = 'busBarSectionId2',
    CASE_FILE = 'caseFile',
    CASE_FORMAT = 'caseFormat',
    CASE_NAME = 'caseName',
    CASE_UUID = 'caseUuid',
    CONTINGENCY_LIST_TYPE = 'contingencyListType',
    CONTINGENCY_NAME = 'contingencyName',
    COUNTRIES_1 = 'countries1',
    COUNTRIES_2 = 'countries2',
    COUNTRIES = 'countries',
    COUNTRY = 'country',
    COUPLING_OMNIBUS = 'couplingOmnibus',
    CURRENT_PARAMETERS = 'currentParameters',
    DELETION_MARK = 'deletionMark',
    DESCRIPTION = 'description',
    DIRECTORY = 'directory',
    ENERGY_SOURCE = 'energySource',
    EQUIPMENT_ID = 'equipmentID',
    EQUIPMENT_NAME = 'equipmentName',
    EQUIPMENT_IDS = 'equipmentIDs',
    EQUIPMENT_TABLE = 'equipmentTable',
    EQUIPMENT_TYPE = 'equipmentType',
    FILTER_TYPE = 'filterType',
    FILTERS = 'filters',
    FOLDER_ID = 'folderId',
    FOLDER_NAME = 'folderName',
    FORMATTED_CASE_PARAMETERS = 'formattedCaseParameters',
    HIGH_SHORT_CIRCUIT_CURRENT_LIMIT = 'highShortCircuitCurrentLimit',
    HIGH_VOLTAGE_LIMIT = 'highVoltageLimit',
    ID = 'id',
    IS_ATTACHMENT_POINT_CREATION = 'isAttachmentPointCreation',
    LOW_SHORT_CIRCUIT_CURRENT_LIMIT = 'lowShortCircuitCurrentLimit',
    LOW_VOLTAGE_LIMIT = 'lowVoltageLimit',
    NAME = 'name',
    NOMINAL_V = 'nominalV',
    NOMINAL_VOLTAGE_1 = 'nominalVoltage1',
    NOMINAL_VOLTAGE_2 = 'nominalVoltage2',
    NOMINAL_VOLTAGE_3 = 'nominalVoltage3',
    NOMINAL_VOLTAGE = 'nominalVoltage',
    OPERATION_TYPE = 'type',
    PREVIOUS_VALUE = 'previousValue',
    PROPERTY_NAME = 'propertyName',
    PROPERTY_OPERATOR = 'propertyOperator',
    PROPERTY = 'PROPERTY',
    PROPERTY_VALUES = 'propertyValues',
    SCRIPT = 'script',
    SECTION_COUNT = 'sectionCount',
    STUDY_NAME = 'studyName',
    SUBSTATION_CREATION = 'substationCreation',
    SUBSTATION_CREATION_ID = 'substationCreationId',
    SUBSTATION_ID = 'substationId',
    SUBSTATION_NAME = 'substationName',
    SWITCH_KIND = 'switchKind',
    SWITCH_KINDS = 'switchKinds',
    SWITCHES_BETWEEN_SECTIONS = 'switchesBetweenSections',
    TOPOLOGY_KIND = 'topologyKind',
    TYPE = 'type',
    VALUE = 'value',
    VALUE_1 = 'value1',
    VALUE_2 = 'value2',
}
