/**
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import { Field } from 'react-querybuilder';
import { CombinatorType, DataType, OperatorType } from './expertFilter.type';
import { FieldType } from '../../../utils/types/fieldType';
import {
    KILO_AMPERE,
    KILO_VOLT,
    MEGA_VAR,
    MEGA_VOLT_AMPERE,
    MEGA_WATT,
    MICRO_SIEMENS,
    OHM,
    SIEMENS,
} from '../../../utils/constants/unitsConstants';
import { ALL_EQUIPMENTS, EquipmentType } from '../../../utils';

export enum RULES {
    EMPTY_RULE = 'emptyRule',
    EMPTY_GROUP = 'emptyGroup',
    INCORRECT_RULE = 'incorrectRule',
    BETWEEN_RULE = 'betweenRule',
}

export const EXPERT_FILTER_QUERY = 'rules';

export const EXPERT_FILTER_EQUIPMENTS: typeof ALL_EQUIPMENTS = {
    [EquipmentType.SUBSTATION]: ALL_EQUIPMENTS[EquipmentType.SUBSTATION],
    [EquipmentType.VOLTAGE_LEVEL]: ALL_EQUIPMENTS[EquipmentType.VOLTAGE_LEVEL],
    [EquipmentType.LINE]: ALL_EQUIPMENTS[EquipmentType.LINE],
    [EquipmentType.TWO_WINDINGS_TRANSFORMER]: ALL_EQUIPMENTS[EquipmentType.TWO_WINDINGS_TRANSFORMER],
    [EquipmentType.THREE_WINDINGS_TRANSFORMER]: ALL_EQUIPMENTS[EquipmentType.THREE_WINDINGS_TRANSFORMER],
    [EquipmentType.GENERATOR]: ALL_EQUIPMENTS[EquipmentType.GENERATOR],
    [EquipmentType.BATTERY]: ALL_EQUIPMENTS[EquipmentType.BATTERY],
    [EquipmentType.LOAD]: ALL_EQUIPMENTS[EquipmentType.LOAD],
    [EquipmentType.SHUNT_COMPENSATOR]: ALL_EQUIPMENTS[EquipmentType.SHUNT_COMPENSATOR],
    [EquipmentType.STATIC_VAR_COMPENSATOR]: ALL_EQUIPMENTS[EquipmentType.STATIC_VAR_COMPENSATOR],
    [EquipmentType.HVDC_LINE]: ALL_EQUIPMENTS[EquipmentType.HVDC_LINE],
    [EquipmentType.DANGLING_LINE]: ALL_EQUIPMENTS[EquipmentType.DANGLING_LINE],
};

export const ENERGY_SOURCE_OPTIONS = [
    { name: 'HYDRO', label: 'Hydro' },
    { name: 'NUCLEAR', label: 'Nuclear' },
    { name: 'WIND', label: 'Wind' },
    { name: 'THERMAL', label: 'Thermal' },
    { name: 'SOLAR', label: 'Solar' },
    { name: 'OTHER', label: 'Other' },
];

export const SHUNT_COMPENSATOR_TYPE_OPTIONS = [
    { name: 'CAPACITOR', label: 'Capacitor' },
    { name: 'REACTOR', label: 'Reactor' },
];

export const LOAD_TYPE_OPTIONS = [
    { name: 'UNDEFINED', label: 'Undefined' },
    { name: 'AUXILIARY', label: 'Auxiliary' },
    { name: 'FICTITIOUS', label: 'Fictitious' },
];

export const RATIO_REGULATION_MODE_OPTIONS = [
    { name: 'VOLTAGE_REGULATION', label: 'VoltageRegulation' },
    { name: 'FIXED_RATIO', label: 'FixedRatio' },
];

export const PHASE_REGULATION_MODE_OPTIONS = [
    { name: 'CURRENT_LIMITER', label: 'CurrentLimiter' },
    { name: 'ACTIVE_POWER_CONTROL', label: 'ActivePowerControl' },
];

export const SVAR_REGULATION_MODE_OPTIONS = [
    { name: 'VOLTAGE', label: 'regulationMode.voltage' },
    { name: 'REACTIVE_POWER', label: 'regulationMode.reactivePower' },
];

export const REGULATION_TYPE_OPTIONS = [
    { name: 'LOCAL', label: 'regulationType.local' },
    { name: 'DISTANT', label: 'regulationType.distant' },
];

export const CONVERTERS_MODE_OPTIONS = [
    {
        name: 'SIDE_1_RECTIFIER_SIDE_2_INVERTER',
        label: 'side1RectifierSide2Inverter',
    },
    {
        name: 'SIDE_1_INVERTER_SIDE_2_RECTIFIER',
        label: 'side1InverterSide2Rectifier',
    },
];

// customName is used to export to the server
export const OPERATOR_OPTIONS = {
    EQUALS: { name: '=', customName: OperatorType.EQUALS, label: 'equality' },
    NOT_EQUALS: {
        name: '!=',
        customName: OperatorType.NOT_EQUALS,
        label: 'notEquality',
    },
    // Number and String
    EXISTS: {
        name: OperatorType.EXISTS,
        customName: OperatorType.EXISTS,
        label: 'exists',
    },
    NOT_EXISTS: {
        name: OperatorType.NOT_EXISTS,
        customName: OperatorType.NOT_EXISTS,
        label: 'not_exists',
    },
    // Number
    LOWER: { name: '<', customName: OperatorType.LOWER, label: 'lessThan' },
    LOWER_OR_EQUALS: {
        name: '<=',
        customName: OperatorType.LOWER_OR_EQUALS,
        label: 'lessOrEqual',
    },
    GREATER: {
        name: '>',
        customName: OperatorType.GREATER,
        label: 'greaterThan',
    },
    GREATER_OR_EQUALS: {
        name: '>=',
        customName: OperatorType.GREATER_OR_EQUALS,
        label: 'greaterOrEqual',
    },
    BETWEEN: {
        name: 'between',
        customName: OperatorType.BETWEEN,
        label: 'between',
    },
    IN: { name: 'in', customName: OperatorType.IN, label: 'in' },
    NOT_IN: { name: 'notIn', customName: OperatorType.NOT_IN, label: 'notIn' },
    // String
    IS: { name: OperatorType.IS, customName: OperatorType.IS, label: 'is' },
    CONTAINS: {
        name: 'contains',
        customName: OperatorType.CONTAINS,
        label: 'contains',
    },
    BEGINS_WITH: {
        name: 'beginsWith',
        customName: OperatorType.BEGINS_WITH,
        label: 'beginsWith',
    },
    ENDS_WITH: {
        name: 'endsWith',
        customName: OperatorType.ENDS_WITH,
        label: 'endsWith',
    },
    IS_PART_OF: {
        name: OperatorType.IS_PART_OF,
        customName: OperatorType.IS_PART_OF,
        label: 'inFilter',
    },
    IS_NOT_PART_OF: {
        name: OperatorType.IS_NOT_PART_OF,
        customName: OperatorType.IS_NOT_PART_OF,
        label: 'notInFilter',
    },
};

export const COMBINATOR_OPTIONS = {
    AND: { name: CombinatorType.AND, label: 'AND' },
    OR: { name: CombinatorType.OR, label: 'OR' },
};

export const FIELDS_OPTIONS = {
    ID: {
        name: FieldType.ID,
        label: 'id',
        dataType: DataType.STRING,
    },
    NAME: {
        name: FieldType.NAME,
        label: 'name',
        dataType: DataType.STRING,
    },
    NOMINAL_VOLTAGE: {
        name: FieldType.NOMINAL_VOLTAGE,
        label: 'vlNominalVoltage',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MIN_P: {
        name: FieldType.MIN_P,
        label: 'minP',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAX_P: {
        name: FieldType.MAX_P,
        label: 'maxP',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    P: {
        name: FieldType.P,
        label: 'p',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    Q: {
        name: FieldType.Q,
        label: 'q',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    P_ABSOLUTE: {
        name: FieldType.P_ABSOLUTE,
        label: 'pAbsolute',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    Q_ABSOLUTE: {
        name: FieldType.Q_ABSOLUTE,
        label: 'qAbsolute',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    TARGET_P: {
        name: FieldType.TARGET_P,
        label: 'targetP',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    TARGET_V: {
        name: FieldType.TARGET_V,
        label: 'targetV',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    TARGET_Q: {
        name: FieldType.TARGET_Q,
        label: 'targetQ',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    ENERGY_SOURCE: {
        name: FieldType.ENERGY_SOURCE,
        label: 'energySource',
        dataType: DataType.ENUM,
        values: ENERGY_SOURCE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'HYDRO',
    },
    COUNTRY: {
        name: FieldType.COUNTRY,
        label: 'country',
        dataType: DataType.ENUM,
        valueEditorType: 'select',
    },
    VOLTAGE_REGULATOR_ON: {
        name: FieldType.VOLTAGE_REGULATOR_ON,
        label: 'voltageRegulatorOn',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    PLANNED_ACTIVE_POWER_SET_POINT: {
        name: FieldType.PLANNED_ACTIVE_POWER_SET_POINT,
        label: 'PlannedActivePowerSetPoint',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    CONNECTED: {
        name: FieldType.CONNECTED,
        label: 'connected',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    RATED_S: {
        name: FieldType.RATED_S,
        label: 'ratedS',
        unit: MEGA_VOLT_AMPERE,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_S1: {
        name: FieldType.RATED_S1,
        label: 'ratedS1',
        unit: MEGA_VOLT_AMPERE,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_S2: {
        name: FieldType.RATED_S2,
        label: 'ratedS2',
        unit: MEGA_VOLT_AMPERE,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_S3: {
        name: FieldType.RATED_S3,
        label: 'ratedS3',
        unit: MEGA_VOLT_AMPERE,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MARGINAL_COST: {
        name: FieldType.MARGINAL_COST,
        label: 'marginalCost',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PLANNED_OUTAGE_RATE: {
        name: FieldType.PLANNED_OUTAGE_RATE,
        label: 'plannedOutageRate',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    FORCED_OUTAGE_RATE: {
        name: FieldType.FORCED_OUTAGE_RATE,
        label: 'forcedOutageRate',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    VOLTAGE_LEVEL_ID: {
        name: FieldType.VOLTAGE_LEVEL_ID,
        label: 'vlId',
        dataType: DataType.STRING,
    },
    P0: {
        name: FieldType.P0,
        label: 'p0',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    Q0: {
        name: FieldType.Q0,
        label: 'q0',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    LOW_VOLTAGE_LIMIT: {
        name: FieldType.LOW_VOLTAGE_LIMIT,
        label: 'lowVoltageLimit',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    HIGH_VOLTAGE_LIMIT: {
        name: FieldType.HIGH_VOLTAGE_LIMIT,
        label: 'highVoltageLimit',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAXIMUM_SECTION_COUNT: {
        name: FieldType.MAXIMUM_SECTION_COUNT,
        label: 'maximumSectionCount',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SECTION_COUNT: {
        name: FieldType.SECTION_COUNT,
        label: 'sectionCount',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_COMPENSATOR_TYPE: {
        name: FieldType.SHUNT_COMPENSATOR_TYPE,
        label: 'shuntCompensatorType',
        dataType: DataType.ENUM,
        values: SHUNT_COMPENSATOR_TYPE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'CAPACITOR',
    },
    MAX_Q_AT_NOMINAL_V: {
        name: FieldType.MAX_Q_AT_NOMINAL_V,
        label: 'maxQAtNominalV',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MIN_Q_AT_NOMINAL_V: {
        name: FieldType.MIN_Q_AT_NOMINAL_V,
        label: 'minQAtNominalV',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    FIX_Q_AT_NOMINAL_V: {
        name: FieldType.FIX_Q_AT_NOMINAL_V,
        label: 'fixQAtNominalV',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SWITCHED_ON_Q_AT_NOMINAL_V: {
        name: FieldType.SWITCHED_ON_Q_AT_NOMINAL_V,
        label: 'SwitchedOnMaxQAtNominalV',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAX_SUSCEPTANCE: {
        name: FieldType.MAX_SUSCEPTANCE,
        label: 'maxSusceptance',
        unit: SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MIN_SUSCEPTANCE: {
        name: FieldType.MIN_SUSCEPTANCE,
        label: 'minSusceptance',
        unit: SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SWITCHED_ON_SUSCEPTANCE: {
        name: FieldType.SWITCHED_ON_SUSCEPTANCE,
        label: 'SwitchedOnMaxSusceptance',
        unit: SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    CONNECTED_1: {
        name: FieldType.CONNECTED_1,
        label: 'terminal1Connected',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    CONNECTED_2: {
        name: FieldType.CONNECTED_2,
        label: 'terminal2Connected',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    CONNECTED_3: {
        name: FieldType.CONNECTED_3,
        label: 'terminal3ConnectedTwt',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    VOLTAGE_LEVEL_ID_1: {
        name: FieldType.VOLTAGE_LEVEL_ID_1,
        label: 'voltageLevelId1',
        dataType: DataType.STRING,
    },
    VOLTAGE_LEVEL_ID_2: {
        name: FieldType.VOLTAGE_LEVEL_ID_2,
        label: 'voltageLevelId2',
        dataType: DataType.STRING,
    },
    VOLTAGE_LEVEL_ID_3: {
        name: FieldType.VOLTAGE_LEVEL_ID_3,
        label: 'voltageLevelId3Twt',
        dataType: DataType.STRING,
    },
    NOMINAL_VOLTAGE_1: {
        name: FieldType.NOMINAL_VOLTAGE_1,
        label: 'nominalVoltage1KV',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    NOMINAL_VOLTAGE_2: {
        name: FieldType.NOMINAL_VOLTAGE_2,
        label: 'nominalVoltage2KV',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    NOMINAL_VOLTAGE_3: {
        name: FieldType.NOMINAL_VOLTAGE_3,
        label: 'nominalVoltage3KVTwt',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_VOLTAGE_1: {
        name: FieldType.RATED_VOLTAGE_1,
        label: 'ratedVoltage1KV',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_VOLTAGE_2: {
        name: FieldType.RATED_VOLTAGE_2,
        label: 'ratedVoltage2KV',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_VOLTAGE_0: {
        name: FieldType.RATED_VOLTAGE_0,
        label: 'ratedVoltage0KVTwt',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATED_VOLTAGE_3: {
        name: FieldType.RATED_VOLTAGE_3,
        label: 'ratedVoltage3KVTwt',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    COUNTRY_1: {
        name: FieldType.COUNTRY_1,
        label: 'country1',
        dataType: DataType.ENUM,
        valueEditorType: 'select',
    },
    COUNTRY_2: {
        name: FieldType.COUNTRY_2,
        label: 'country2',
        dataType: DataType.ENUM,
        valueEditorType: 'select',
    },
    SERIE_RESISTANCE: {
        name: FieldType.SERIE_RESISTANCE,
        label: 'seriesResistance',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_RESISTANCE_1: {
        name: FieldType.SERIE_RESISTANCE_1,
        label: 'seriesResistance1',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_RESISTANCE_2: {
        name: FieldType.SERIE_RESISTANCE_2,
        label: 'seriesResistance2',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_RESISTANCE_3: {
        name: FieldType.SERIE_RESISTANCE_3,
        label: 'seriesResistance3',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_REACTANCE: {
        name: FieldType.SERIE_REACTANCE,
        label: 'seriesReactance',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_REACTANCE_1: {
        name: FieldType.SERIE_REACTANCE_1,
        label: 'seriesReactance1',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_REACTANCE_2: {
        name: FieldType.SERIE_REACTANCE_2,
        label: 'seriesReactance2',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SERIE_REACTANCE_3: {
        name: FieldType.SERIE_REACTANCE_3,
        label: 'seriesReactance3',
        unit: OHM,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_CONDUCTANCE_1: {
        name: FieldType.SHUNT_CONDUCTANCE_1,
        label: 'shuntConductance1',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_CONDUCTANCE_2: {
        name: FieldType.SHUNT_CONDUCTANCE_2,
        label: 'shuntConductance2',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_SUSCEPTANCE_1: {
        name: FieldType.SHUNT_SUSCEPTANCE_1,
        label: 'shuntSusceptance1',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_SUSCEPTANCE_2: {
        name: FieldType.SHUNT_SUSCEPTANCE_2,
        label: 'shuntSusceptance2',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_CONDUCTANCE: {
        name: FieldType.MAGNETIZING_CONDUCTANCE,
        label: 'magnetizingConductance',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_CONDUCTANCE_1: {
        name: FieldType.MAGNETIZING_CONDUCTANCE_1,
        label: 'magnetizingConductance1',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_CONDUCTANCE_2: {
        name: FieldType.MAGNETIZING_CONDUCTANCE_2,
        label: 'magnetizingConductance2',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_CONDUCTANCE_3: {
        name: FieldType.MAGNETIZING_CONDUCTANCE_3,
        label: 'magnetizingConductance3',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_SUSCEPTANCE: {
        name: FieldType.MAGNETIZING_SUSCEPTANCE,
        label: 'magnetizingSusceptance',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_SUSCEPTANCE_1: {
        name: FieldType.MAGNETIZING_SUSCEPTANCE_1,
        label: 'magnetizingSusceptance1',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_SUSCEPTANCE_2: {
        name: FieldType.MAGNETIZING_SUSCEPTANCE_2,
        label: 'magnetizingSusceptance2',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    MAGNETIZING_SUSCEPTANCE_3: {
        name: FieldType.MAGNETIZING_SUSCEPTANCE_3,
        label: 'magnetizingSusceptance3',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    LOAD_TYPE: {
        name: FieldType.LOAD_TYPE,
        label: 'loadType',
        dataType: DataType.ENUM,
        values: LOAD_TYPE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'UNDEFINED',
    },
    HAS_RATIO_TAP_CHANGER: {
        name: FieldType.HAS_RATIO_TAP_CHANGER,
        label: 'hasRatioTapChanger',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    HAS_RATIO_TAP_CHANGER_1: {
        name: FieldType.HAS_RATIO_TAP_CHANGER_1,
        label: 'hasRatioTapChanger1',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    HAS_RATIO_TAP_CHANGER_2: {
        name: FieldType.HAS_RATIO_TAP_CHANGER_2,
        label: 'hasRatioTapChanger2',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    HAS_RATIO_TAP_CHANGER_3: {
        name: FieldType.HAS_RATIO_TAP_CHANGER_3,
        label: 'hasRatioTapChanger3',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    LOAD_TAP_CHANGING_CAPABILITIES: {
        name: FieldType.LOAD_TAP_CHANGING_CAPABILITIES,
        label: 'loadTapChangingCapabilities',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    LOAD_TAP_CHANGING_CAPABILITIES_1: {
        name: FieldType.LOAD_TAP_CHANGING_CAPABILITIES_1,
        label: 'loadTapChangingCapabilities1',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    LOAD_TAP_CHANGING_CAPABILITIES_2: {
        name: FieldType.LOAD_TAP_CHANGING_CAPABILITIES_2,
        label: 'loadTapChangingCapabilities2',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    LOAD_TAP_CHANGING_CAPABILITIES_3: {
        name: FieldType.LOAD_TAP_CHANGING_CAPABILITIES_3,
        label: 'loadTapChangingCapabilities3',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    RATIO_REGULATION_MODE: {
        name: FieldType.RATIO_REGULATION_MODE,
        label: 'ratioRegulationMode',
        dataType: DataType.ENUM,
        values: RATIO_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'VOLTAGE_REGULATION',
    },
    RATIO_REGULATION_MODE_1: {
        name: FieldType.RATIO_REGULATION_MODE_1,
        label: 'ratioRegulationMode1',
        dataType: DataType.ENUM,
        values: RATIO_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'VOLTAGE_REGULATION',
    },
    RATIO_REGULATION_MODE_2: {
        name: FieldType.RATIO_REGULATION_MODE_2,
        label: 'ratioRegulationMode2',
        dataType: DataType.ENUM,
        values: RATIO_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'VOLTAGE_REGULATION',
    },
    RATIO_REGULATION_MODE_3: {
        name: FieldType.RATIO_REGULATION_MODE_3,
        label: 'ratioRegulationMode3',
        dataType: DataType.ENUM,
        values: RATIO_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'VOLTAGE_REGULATION',
    },
    RATIO_TARGET_V: {
        name: FieldType.RATIO_TARGET_V,
        label: 'ratioTargetV',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATIO_TARGET_V1: {
        name: FieldType.RATIO_TARGET_V1,
        label: 'ratioTargetV1',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATIO_TARGET_V2: {
        name: FieldType.RATIO_TARGET_V2,
        label: 'ratioTargetV2',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    RATIO_TARGET_V3: {
        name: FieldType.RATIO_TARGET_V3,
        label: 'ratioTargetV3',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    HAS_PHASE_TAP_CHANGER: {
        name: FieldType.HAS_PHASE_TAP_CHANGER,
        label: 'hasPhaseTapChanger',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    HAS_PHASE_TAP_CHANGER_1: {
        name: FieldType.HAS_PHASE_TAP_CHANGER_1,
        label: 'hasPhaseTapChanger1',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    HAS_PHASE_TAP_CHANGER_2: {
        name: FieldType.HAS_PHASE_TAP_CHANGER_2,
        label: 'hasPhaseTapChanger2',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    HAS_PHASE_TAP_CHANGER_3: {
        name: FieldType.HAS_PHASE_TAP_CHANGER_3,
        label: 'hasPhaseTapChanger3',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    PHASE_REGULATION_MODE: {
        name: FieldType.PHASE_REGULATION_MODE,
        label: 'phaseRegulationMode',
        dataType: DataType.ENUM,
        values: PHASE_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'CURRENT_LIMITER',
    },
    PHASE_REGULATION_MODE_1: {
        name: FieldType.PHASE_REGULATION_MODE_1,
        label: 'phaseRegulationMode1',
        dataType: DataType.ENUM,
        values: PHASE_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'CURRENT_LIMITER',
    },
    PHASE_REGULATION_MODE_2: {
        name: FieldType.PHASE_REGULATION_MODE_2,
        label: 'phaseRegulationMode2',
        dataType: DataType.ENUM,
        values: PHASE_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'CURRENT_LIMITER',
    },
    PHASE_REGULATION_MODE_3: {
        name: FieldType.PHASE_REGULATION_MODE_3,
        label: 'phaseRegulationMode3',
        dataType: DataType.ENUM,
        values: PHASE_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'CURRENT_LIMITER',
    },
    PHASE_REGULATION_VALUE: {
        name: FieldType.PHASE_REGULATION_VALUE,
        label: 'phaseRegulationValue',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PHASE_REGULATION_VALUE_1: {
        name: FieldType.PHASE_REGULATION_VALUE_1,
        label: 'phaseRegulationValue1',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PHASE_REGULATION_VALUE_2: {
        name: FieldType.PHASE_REGULATION_VALUE_2,
        label: 'phaseRegulationValue2',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PHASE_REGULATION_VALUE_3: {
        name: FieldType.PHASE_REGULATION_VALUE_3,
        label: 'phaseRegulationValue3',
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PROPERTY: {
        name: FieldType.FREE_PROPERTIES,
        label: 'property',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    SUBSTATION_PROPERTY: {
        name: FieldType.SUBSTATION_PROPERTIES,
        label: 'substationProperty',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    SUBSTATION_PROPERTY_1: {
        name: FieldType.SUBSTATION_PROPERTIES_1,
        label: 'substationProperty1',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    SUBSTATION_PROPERTY_2: {
        name: FieldType.SUBSTATION_PROPERTIES_2,
        label: 'substationProperty2',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    VOLTAGE_LEVEL_PROPERTY: {
        name: FieldType.VOLTAGE_LEVEL_PROPERTIES,
        label: 'voltageLevelProperty',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    VOLTAGE_LEVEL_PROPERTY_1: {
        name: FieldType.VOLTAGE_LEVEL_PROPERTIES_1,
        label: 'voltageLevelProperty1',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    VOLTAGE_LEVEL_PROPERTY_2: {
        name: FieldType.VOLTAGE_LEVEL_PROPERTIES_2,
        label: 'voltageLevelProperty2',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    VOLTAGE_LEVEL_PROPERTY_3: {
        name: FieldType.VOLTAGE_LEVEL_PROPERTIES_3,
        label: 'voltageLevelProperty3Twt',
        dataType: DataType.PROPERTY,
        valueEditorType: 'select',
        defaultValue: '',
    },
    SVAR_REGULATION_MODE: {
        name: FieldType.SVAR_REGULATION_MODE,
        label: 'regulationMode',
        dataType: DataType.ENUM,
        values: SVAR_REGULATION_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'VOLTAGE',
    },
    VOLTAGE_SET_POINT: {
        name: FieldType.VOLTAGE_SET_POINT,
        label: 'voltageSetPoint',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    ACTIVE_POWER_SET_POINT: {
        name: FieldType.ACTIVE_POWER_SET_POINT,
        label: 'activePowerSetPoint',
        unit: MEGA_WATT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    REACTIVE_POWER_SET_POINT: {
        name: FieldType.REACTIVE_POWER_SET_POINT,
        label: 'reactivePowerSetPoint',
        unit: MEGA_VAR,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    REMOTE_REGULATED_TERMINAL: {
        // composite rule
        name: FieldType.REMOTE_REGULATED_TERMINAL,
        label: 'remoteRegulatedTerminal',
        dataType: DataType.COMBINATOR,
        combinator: CombinatorType.AND,
        children: {
            REGULATING_TERMINAL_VL_ID: {
                name: FieldType.REGULATING_TERMINAL_VL_ID,
                label: 'regulatingTerminalVLId',
                dataType: DataType.STRING,
                operators: [OPERATOR_OPTIONS.IS],
            },
            REGULATING_TERMINAL_CONNECTABLE_ID: {
                name: FieldType.REGULATING_TERMINAL_CONNECTABLE_ID,
                label: 'regulatingTerminalConnectableId',
                dataType: DataType.STRING,
                operators: [OPERATOR_OPTIONS.IS],
            },
        },
    },
    REGULATION_TYPE: {
        name: FieldType.REGULATION_TYPE,
        label: 'regulationType',
        dataType: DataType.ENUM,
        values: REGULATION_TYPE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'LOCAL',
    },
    AUTOMATE: {
        name: FieldType.AUTOMATE,
        label: 'automate',
        dataType: DataType.BOOLEAN,
    },
    LOW_VOLTAGE_SET_POINT: {
        name: FieldType.LOW_VOLTAGE_SET_POINT,
        label: 'lowVoltageSetPoint',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    HIGH_VOLTAGE_SET_POINT: {
        name: FieldType.HIGH_VOLTAGE_SET_POINT,
        label: 'highVoltageSetPoint',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    LOW_VOLTAGE_THRESHOLD: {
        name: FieldType.LOW_VOLTAGE_THRESHOLD,
        label: 'lowVoltageThreshold',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    HIGH_VOLTAGE_THRESHOLD: {
        name: FieldType.HIGH_VOLTAGE_THRESHOLD,
        label: 'highVoltageThreshold',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SUSCEPTANCE_FIX: {
        name: FieldType.SUSCEPTANCE_FIX,
        label: 'susceptanceFix',
        unit: SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_SUSCEPTANCE: {
        name: FieldType.SHUNT_SUSCEPTANCE,
        label: 'shuntSusceptance',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SHUNT_CONDUCTANCE: {
        name: FieldType.SHUNT_CONDUCTANCE,
        label: 'shuntConductance',
        unit: MICRO_SIEMENS,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PAIRED: {
        name: FieldType.PAIRED,
        label: 'paired',
        dataType: DataType.BOOLEAN,
        defaultValue: false,
        valueEditorType: 'switch',
    },
    CONVERTER_STATION_ID_1: {
        name: FieldType.CONVERTER_STATION_ID_1,
        label: 'converterStationId1',
        dataType: DataType.STRING,
    },
    CONVERTER_STATION_ID_2: {
        name: FieldType.CONVERTER_STATION_ID_2,
        label: 'converterStationId2',
        dataType: DataType.STRING,
    },
    CONVERTERS_MODE: {
        name: FieldType.CONVERTERS_MODE,
        label: 'convertersMode',
        dataType: DataType.ENUM,
        values: CONVERTERS_MODE_OPTIONS,
        valueEditorType: 'select',
        defaultValue: 'SIDE_1_RECTIFIER_SIDE_2_INVERTER',
    },
    CONVERTER_STATION_NOMINAL_VOLTAGE_1: {
        name: FieldType.CONVERTER_STATION_NOMINAL_VOLTAGE_1,
        label: 'converterStationNominalVoltage1',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    CONVERTER_STATION_NOMINAL_VOLTAGE_2: {
        name: FieldType.CONVERTER_STATION_NOMINAL_VOLTAGE_2,
        label: 'converterStationNominalVoltage2',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    DC_NOMINAL_VOLTAGE: {
        name: FieldType.DC_NOMINAL_VOLTAGE,
        label: 'dcNominalVoltage',
        unit: KILO_VOLT,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    PAIRING_KEY: {
        name: FieldType.PAIRING_KEY,
        label: 'pairingKey',
        dataType: DataType.STRING,
    },
    TIE_LINE_ID: {
        name: FieldType.TIE_LINE_ID,
        label: 'tieLineId',
        dataType: DataType.STRING,
    },
    LOW_SHORT_CIRCUIT_CURRENT_LIMIT: {
        name: FieldType.LOW_SHORT_CIRCUIT_CURRENT_LIMIT,
        label: 'lowShortCircuitCurrentLimit',
        unit: KILO_AMPERE,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    HIGH_SHORT_CIRCUIT_CURRENT_LIMIT: {
        name: FieldType.HIGH_SHORT_CIRCUIT_CURRENT_LIMIT,
        label: 'highShortCircuitCurrentLimit',
        unit: KILO_AMPERE,
        dataType: DataType.NUMBER,
        inputType: 'number',
    },
    SUBSTATION_ID: {
        name: FieldType.SUBSTATION_ID,
        label: 'substationId',
        dataType: DataType.STRING,
    },
    SUBSTATION_ID_1: {
        name: FieldType.SUBSTATION_ID_1,
        label: 'substationId1',
        dataType: DataType.STRING,
    },
    SUBSTATION_ID_2: {
        name: FieldType.SUBSTATION_ID_2,
        label: 'substationId2',
        dataType: DataType.STRING,
    },
};

export const EXPERT_FILTER_FIELDS: Record<string, Field[]> = {
    SUBSTATION: [FIELDS_OPTIONS.ID, FIELDS_OPTIONS.NAME, FIELDS_OPTIONS.COUNTRY, FIELDS_OPTIONS.PROPERTY],
    VOLTAGE_LEVEL: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.LOW_VOLTAGE_LIMIT,
        FIELDS_OPTIONS.HIGH_VOLTAGE_LIMIT,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.LOW_SHORT_CIRCUIT_CURRENT_LIMIT,
        FIELDS_OPTIONS.HIGH_SHORT_CIRCUIT_CURRENT_LIMIT,
    ],
    LINE: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY_1,
        FIELDS_OPTIONS.COUNTRY_2,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_1,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_2,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE_1,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE_2,
        FIELDS_OPTIONS.CONNECTED_1,
        FIELDS_OPTIONS.CONNECTED_2,
        FIELDS_OPTIONS.SERIE_RESISTANCE,
        FIELDS_OPTIONS.SERIE_REACTANCE,
        FIELDS_OPTIONS.SHUNT_CONDUCTANCE_1,
        FIELDS_OPTIONS.SHUNT_CONDUCTANCE_2,
        FIELDS_OPTIONS.SHUNT_SUSCEPTANCE_1,
        FIELDS_OPTIONS.SHUNT_SUSCEPTANCE_2,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID_1,
        FIELDS_OPTIONS.SUBSTATION_ID_2,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY_1,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY_2,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_1,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_2,
    ],
    TWO_WINDINGS_TRANSFORMER: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_1,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_2,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE_1,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE_2,
        FIELDS_OPTIONS.RATED_VOLTAGE_1,
        FIELDS_OPTIONS.RATED_VOLTAGE_2,
        FIELDS_OPTIONS.CONNECTED_1,
        FIELDS_OPTIONS.CONNECTED_2,
        FIELDS_OPTIONS.RATED_S,
        FIELDS_OPTIONS.SERIE_RESISTANCE,
        FIELDS_OPTIONS.SERIE_REACTANCE,
        FIELDS_OPTIONS.MAGNETIZING_CONDUCTANCE,
        FIELDS_OPTIONS.MAGNETIZING_SUSCEPTANCE,
        FIELDS_OPTIONS.HAS_RATIO_TAP_CHANGER,
        FIELDS_OPTIONS.LOAD_TAP_CHANGING_CAPABILITIES,
        FIELDS_OPTIONS.RATIO_REGULATION_MODE,
        FIELDS_OPTIONS.RATIO_TARGET_V,
        FIELDS_OPTIONS.HAS_PHASE_TAP_CHANGER,
        FIELDS_OPTIONS.PHASE_REGULATION_MODE,
        FIELDS_OPTIONS.PHASE_REGULATION_VALUE,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_1,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_2,
    ],
    THREE_WINDINGS_TRANSFORMER: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY,
        {
            ...FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_1,
            label: `${FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_1.label}Twt`,
        },
        {
            ...FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_2,
            label: `${FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_2.label}Twt`,
        },
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_3,
        {
            ...FIELDS_OPTIONS.NOMINAL_VOLTAGE_1,
            label: `${FIELDS_OPTIONS.NOMINAL_VOLTAGE_1.label}Twt`,
        },
        {
            ...FIELDS_OPTIONS.NOMINAL_VOLTAGE_2,
            label: `${FIELDS_OPTIONS.NOMINAL_VOLTAGE_2.label}Twt`,
        },
        FIELDS_OPTIONS.NOMINAL_VOLTAGE_3,
        {
            ...FIELDS_OPTIONS.CONNECTED_1,
            label: `${FIELDS_OPTIONS.CONNECTED_1.label}Twt`,
        },
        {
            ...FIELDS_OPTIONS.CONNECTED_2,
            label: `${FIELDS_OPTIONS.CONNECTED_2.label}Twt`,
        },
        FIELDS_OPTIONS.CONNECTED_3,
        FIELDS_OPTIONS.RATED_VOLTAGE_0,
        {
            ...FIELDS_OPTIONS.RATED_VOLTAGE_1,
            label: `${FIELDS_OPTIONS.RATED_VOLTAGE_1.label}Twt`,
        },
        {
            ...FIELDS_OPTIONS.RATED_VOLTAGE_2,
            label: `${FIELDS_OPTIONS.RATED_VOLTAGE_2.label}Twt`,
        },
        FIELDS_OPTIONS.RATED_VOLTAGE_3,
        FIELDS_OPTIONS.RATED_S1,
        FIELDS_OPTIONS.RATED_S2,
        FIELDS_OPTIONS.RATED_S3,
        FIELDS_OPTIONS.SERIE_RESISTANCE_1,
        FIELDS_OPTIONS.SERIE_RESISTANCE_2,
        FIELDS_OPTIONS.SERIE_RESISTANCE_3,
        FIELDS_OPTIONS.SERIE_REACTANCE_1,
        FIELDS_OPTIONS.SERIE_REACTANCE_2,
        FIELDS_OPTIONS.SERIE_REACTANCE_3,
        FIELDS_OPTIONS.MAGNETIZING_CONDUCTANCE_1,
        FIELDS_OPTIONS.MAGNETIZING_CONDUCTANCE_2,
        FIELDS_OPTIONS.MAGNETIZING_CONDUCTANCE_3,
        FIELDS_OPTIONS.MAGNETIZING_SUSCEPTANCE_1,
        FIELDS_OPTIONS.MAGNETIZING_SUSCEPTANCE_2,
        FIELDS_OPTIONS.MAGNETIZING_SUSCEPTANCE_3,
        FIELDS_OPTIONS.HAS_RATIO_TAP_CHANGER_1,
        FIELDS_OPTIONS.HAS_RATIO_TAP_CHANGER_2,
        FIELDS_OPTIONS.HAS_RATIO_TAP_CHANGER_3,
        FIELDS_OPTIONS.LOAD_TAP_CHANGING_CAPABILITIES_1,
        FIELDS_OPTIONS.LOAD_TAP_CHANGING_CAPABILITIES_2,
        FIELDS_OPTIONS.LOAD_TAP_CHANGING_CAPABILITIES_3,
        FIELDS_OPTIONS.RATIO_TARGET_V1,
        FIELDS_OPTIONS.RATIO_TARGET_V2,
        FIELDS_OPTIONS.RATIO_TARGET_V3,
        FIELDS_OPTIONS.RATIO_REGULATION_MODE_1,
        FIELDS_OPTIONS.RATIO_REGULATION_MODE_2,
        FIELDS_OPTIONS.RATIO_REGULATION_MODE_3,
        FIELDS_OPTIONS.HAS_PHASE_TAP_CHANGER_1,
        FIELDS_OPTIONS.HAS_PHASE_TAP_CHANGER_2,
        FIELDS_OPTIONS.HAS_PHASE_TAP_CHANGER_3,
        FIELDS_OPTIONS.PHASE_REGULATION_VALUE_1,
        FIELDS_OPTIONS.PHASE_REGULATION_VALUE_2,
        FIELDS_OPTIONS.PHASE_REGULATION_VALUE_3,
        FIELDS_OPTIONS.PHASE_REGULATION_MODE_1,
        FIELDS_OPTIONS.PHASE_REGULATION_MODE_2,
        FIELDS_OPTIONS.PHASE_REGULATION_MODE_3,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        {
            ...FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_1,
            label: `${FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_1.label}Twt`,
        },
        {
            ...FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_2,
            label: `${FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_2.label}Twt`,
        },
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_3,
    ],
    GENERATOR: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.ENERGY_SOURCE,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.CONNECTED,
        FIELDS_OPTIONS.MIN_P,
        FIELDS_OPTIONS.MAX_P,
        FIELDS_OPTIONS.RATED_S,
        FIELDS_OPTIONS.TARGET_P,
        FIELDS_OPTIONS.TARGET_Q,
        FIELDS_OPTIONS.VOLTAGE_REGULATOR_ON,
        FIELDS_OPTIONS.TARGET_V,
        FIELDS_OPTIONS.PLANNED_ACTIVE_POWER_SET_POINT,
        FIELDS_OPTIONS.MARGINAL_COST,
        FIELDS_OPTIONS.PLANNED_OUTAGE_RATE,
        FIELDS_OPTIONS.FORCED_OUTAGE_RATE,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY,
    ],
    BATTERY: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.CONNECTED,
        FIELDS_OPTIONS.MIN_P,
        FIELDS_OPTIONS.MAX_P,
        FIELDS_OPTIONS.TARGET_P,
        FIELDS_OPTIONS.TARGET_Q,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY,
    ],
    LOAD: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.LOAD_TYPE,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.CONNECTED,
        FIELDS_OPTIONS.P0,
        FIELDS_OPTIONS.Q0,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY,
    ],
    SHUNT_COMPENSATOR: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.SHUNT_COMPENSATOR_TYPE,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.CONNECTED,
        FIELDS_OPTIONS.MAXIMUM_SECTION_COUNT,
        FIELDS_OPTIONS.SECTION_COUNT,
        FIELDS_OPTIONS.MAX_Q_AT_NOMINAL_V,
        FIELDS_OPTIONS.SWITCHED_ON_Q_AT_NOMINAL_V,
        FIELDS_OPTIONS.MAX_SUSCEPTANCE,
        FIELDS_OPTIONS.SWITCHED_ON_SUSCEPTANCE,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY,
    ],
    STATIC_VAR_COMPENSATOR: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.CONNECTED,
        // customize label
        {
            ...FIELDS_OPTIONS.MAX_Q_AT_NOMINAL_V,
            label: `${FIELDS_OPTIONS.MAX_Q_AT_NOMINAL_V.label}.svar`,
        },
        {
            ...FIELDS_OPTIONS.MIN_Q_AT_NOMINAL_V,
            label: `${FIELDS_OPTIONS.MIN_Q_AT_NOMINAL_V.label}.svar`,
        },
        // customize label
        {
            ...FIELDS_OPTIONS.MAX_SUSCEPTANCE,
            label: `${FIELDS_OPTIONS.MAX_SUSCEPTANCE.label}.svar`,
        },
        {
            ...FIELDS_OPTIONS.MIN_SUSCEPTANCE,
            label: `${FIELDS_OPTIONS.MIN_SUSCEPTANCE.label}.svar`,
        },
        FIELDS_OPTIONS.SVAR_REGULATION_MODE,
        FIELDS_OPTIONS.REGULATION_TYPE,
        FIELDS_OPTIONS.REMOTE_REGULATED_TERMINAL,
        FIELDS_OPTIONS.VOLTAGE_SET_POINT,
        FIELDS_OPTIONS.REACTIVE_POWER_SET_POINT,
        FIELDS_OPTIONS.AUTOMATE,
        FIELDS_OPTIONS.HIGH_VOLTAGE_SET_POINT,
        FIELDS_OPTIONS.LOW_VOLTAGE_SET_POINT,
        FIELDS_OPTIONS.HIGH_VOLTAGE_THRESHOLD,
        FIELDS_OPTIONS.LOW_VOLTAGE_THRESHOLD,
        {
            ...FIELDS_OPTIONS.FIX_Q_AT_NOMINAL_V,
            label: `${FIELDS_OPTIONS.FIX_Q_AT_NOMINAL_V.label}.svar`,
        },
        FIELDS_OPTIONS.SUSCEPTANCE_FIX,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY,
    ],
    HVDC_LINE: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY_1,
        FIELDS_OPTIONS.COUNTRY_2,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_1,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID_2,
        FIELDS_OPTIONS.CONVERTER_STATION_ID_1,
        FIELDS_OPTIONS.CONVERTER_STATION_ID_2,
        FIELDS_OPTIONS.CONNECTED_1,
        FIELDS_OPTIONS.CONNECTED_2,
        FIELDS_OPTIONS.CONVERTER_STATION_NOMINAL_VOLTAGE_1,
        FIELDS_OPTIONS.CONVERTER_STATION_NOMINAL_VOLTAGE_2,
        FIELDS_OPTIONS.DC_NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.SERIE_RESISTANCE,
        FIELDS_OPTIONS.MAX_P,
        FIELDS_OPTIONS.ACTIVE_POWER_SET_POINT,
        FIELDS_OPTIONS.CONVERTERS_MODE,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID_1,
        FIELDS_OPTIONS.SUBSTATION_ID_2,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY_1,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY_2,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_1,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY_2,
    ],
    DANGLING_LINE: [
        FIELDS_OPTIONS.ID,
        FIELDS_OPTIONS.NAME,
        FIELDS_OPTIONS.COUNTRY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_ID,
        FIELDS_OPTIONS.NOMINAL_VOLTAGE,
        FIELDS_OPTIONS.TIE_LINE_ID,
        FIELDS_OPTIONS.CONNECTED,
        FIELDS_OPTIONS.P0,
        FIELDS_OPTIONS.Q0,
        FIELDS_OPTIONS.SERIE_RESISTANCE,
        FIELDS_OPTIONS.SERIE_REACTANCE,
        FIELDS_OPTIONS.SHUNT_SUSCEPTANCE,
        FIELDS_OPTIONS.SHUNT_CONDUCTANCE,
        FIELDS_OPTIONS.PAIRED,
        FIELDS_OPTIONS.PAIRING_KEY,
        FIELDS_OPTIONS.PROPERTY,
        FIELDS_OPTIONS.SUBSTATION_ID,
        FIELDS_OPTIONS.SUBSTATION_PROPERTY,
        FIELDS_OPTIONS.VOLTAGE_LEVEL_PROPERTY,
    ],
};
